services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres.kjrucbvilemgnrtlysyq
      POSTGRES_PASSWORD: BlueVending_1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    container_name: vending-machine-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.kjrucbvilemgnrtlysyq
      - DB_PASSWORD=BlueVending_1234
      - DB_NAME=postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: